use_frameworks!

platform :ios, '8.0'

target 'MYKit_Example' do
  pod 'MYKit', :path => '../'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'MJRefresh', '~> 3.1.15.3'
  target 'MYKit_Tests' do
    inherit! :search_paths

    
  end
end
